version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - portainer-network

  postgres-volume-test:
    image: postgres:15-alpine
    container_name: postgres-volume-test
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - postgres_volume_data:/var/lib/postgresql/data
    networks:
      - portainer-network

volumes:
  portainer_data:
  postgres_volume_data:

networks:
  portainer-network:
    driver: bridge